site_name: My Docs
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - javascript
        - c#
        - html
        - json

markdown_extensions:
    - admonition
        