site_name: docs.jwk.nz
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - javascript
        - c#
        - html
        - json

nav:
    - Home: index.md
    - Dotnet Core: /dotnet_core/

markdown_extensions:
    - toc:
        permalink: 
    - admonition

copyright: Copyright &copy; 2019 and maintained by <a href="https://twitter.com/jwknz">Jeff Kranenburg</a>

plugins:
    - search
        